moduledir './modules/'
mod 'elastic-kibana', '5.0.1'
mod 'elastic-logstash', '5.3.0'
mod 'puppetlabs-stdlib', '4.17.1'
mod 'puppetlabs-java', '2.1.0'
mod 'puppet-archive', '1.3.0'
mod 'maestrodev-wget', '1.7.3'
