moduledir './modules/'
mod 'elastic-elasticsearch', '5.3.1'
mod 'puppetlabs-apt', '4.1.0'
mod 'puppetlabs-stdlib', '4.17.1'
mod 'richardc-datacat', '0.6.2'
mod 'puppetlabs-java', '2.1.0'
mod 'puppet-archive', '1.3.0'
mod 'puppet-yum', '2.0.0'
mod 'puppetlabs-concat', '4.0.1'
mod 'elastic-kibana', '5.0.1'
